[2025-01-27T19:44:56.319-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_manual.change_jsonfile_manual manual__2025-01-27T22:44:43+00:00 [queued]>
[2025-01-27T19:44:56.322-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_manual.change_jsonfile_manual manual__2025-01-27T22:44:43+00:00 [queued]>
[2025-01-27T19:44:56.322-0300] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-27T19:44:56.412-0300] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): change_jsonfile_manual> on 2025-01-27 22:44:43+00:00
[2025-01-27T19:44:56.416-0300] {standard_task_runner.py:60} INFO - Started process 196406 to run task
[2025-01-27T19:44:56.418-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_manual', 'change_jsonfile_manual', 'manual__2025-01-27T22:44:43+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/step2_manual.py', '--cfg-path', '/tmp/tmpw_r2ej5d']
[2025-01-27T19:44:56.420-0300] {standard_task_runner.py:88} INFO - Job 78: Subtask change_jsonfile_manual
[2025-01-27T19:44:56.536-0300] {task_command.py:423} INFO - Running <TaskInstance: load_data_manual.change_jsonfile_manual manual__2025-01-27T22:44:43+00:00 [running]> on host victor-MS-7C52
[2025-01-27T19:44:57.056-0300] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data_manual' AIRFLOW_CTX_TASK_ID='change_jsonfile_manual' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T22:44:43+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T22:44:43+00:00'
[2025-01-27T19:44:57.057-0300] {logging_mixin.py:188} INFO - ERRO: O diretório data/csv/2025-01-02/ não existe!
[2025-01-27T19:44:57.057-0300] {python.py:201} INFO - Done. Returned value was: None
[2025-01-27T19:44:57.059-0300] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=load_data_manual, task_id=change_jsonfile_manual, execution_date=20250127T224443, start_date=20250127T224456, end_date=20250127T224457
[2025-01-27T19:44:57.152-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-27T19:44:57.163-0300] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
